It-s-My-House/MyHouseClient

Assets/Settings/URP-Balanced.asset
Assets/Settings/URP-Performant.asset

- 집 주인 애니메이션 
- 집 주인 에셋 
- 집 주인 프리팹
- 집 주인 컨트롤러 추가

[MERGE]집주인 기능 병합

---

Assets/Scripts/Melee.cs
Assets/Scripts/Person.cs
Assets/Scripts/Status.cs
Assets/Scripts/Weapon.cs

[FEAT] 근접 공격으로 데미지 넣기

---

Assets/Scripts/TPSCameraController.cs

카메라 방향이 캐릭터 이동 방향에 종속되던 문제 해결 및 TPS 카메라 기본 완성

[FEAT] TPS 카메라 기본 완성

---

Assets/Scenes/Homeowner.unity

[CHORE] 집주인 TPSCamera 적용

---

Assets/Materials/BloodEffectMaterials.meta
Assets/Materials/BloodEffectMaterials/BloodParticleA.mat
Assets/Materials/BloodEffectMaterials/BloodParticleA.mat.meta
Assets/Materials/BloodEffectMaterials/TinyFireMaterial.mat
Assets/Materials/BloodEffectMaterials/TinyFireMaterial.mat.meta
Assets/Prefabs/BloodEffect.meta
Assets/Prefabs/BloodEffect/BloodA.prefab
Assets/Prefabs/BloodEffect/BloodA.prefab.meta
Assets/Prefabs/BloodEffect/BloodB.prefab
Assets/Prefabs/BloodEffect/BloodB.prefab.meta
Assets/Prefabs/BloodEffect/TinyFire.prefab
Assets/Prefabs/BloodEffect/TinyFire.prefab.meta

[ADD] BloodEffect 관련 에셋 추가

---

Assets/Animations/GhostAnimations/AnimatorGhost.controller
Assets/Animations/GhostAnimations/ghost_attack.anim
Assets/Animations/HouseownerAnimations/HouseownerAnimationController.controller
Assets/Animations/RobberAnimations/RobberAnimationController.controller
Assets/Prefabs/vfxgreen.prefab
Assets/Prefabs/vfxred.prefab
Assets/Scenes/IntegrateScene.unity
Assets/Scenes/LoadingScene.unity
Assets/Scripts/ChatServer.cs
Assets/Scripts/Item/StatusItem.cs
Assets/Scripts/Lobby/LobbyBrowseUI.cs
Assets/Scripts/Lobby/NetworkGameManager.cs
Assets/Scripts/Managers/SoundManager.cs
Assets/Scripts/Monster/Monster.cs
Assets/Scripts/Person.cs
Assets/Scripts/PlayerController.cs
Assets/Scripts/Status.cs
Assets/Scripts/UI/InGameUI.cs
Assets/Scripts/Weapon/Gun.cs
Assets/Scripts/Weapon/Melee.cs
ProjectSettings/TagManager.asset

- NGO 적용을 위한 애니메이션 블렌드 해제
- 플레이어 및 몬스터 피해 시 출혈 효과
- 플레이어 및 몬스터 공격 시 출혈 효과
- 점프 후 애니메이션 이전 상태를 기반으로 재생하게 하기
- 아이템 획득 적용하기

데모 촬영 전 Merge

---

Assets/Scenes/IntegrateScene.unity
Assets/Scenes/LoadingScene.unity
Assets/Scripts/Weapon/Melee.cs
Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/EditorBuildSettings.asset

- 출혈 효과 안나오는 문제 해결
- 데모 촬영을 위한 프로젝트 설정 변경

캡스톤디자인 데모 촬영을 위한 개발 내용 Merge

---

Assets/Scenes/IntegrateScene.unity
Assets/Scripts/CameraController.cs
Assets/Scripts/CameraController.cs.meta
Assets/Scripts/PlayerMove.cs
Assets/Scripts/PlayerMove.cs.meta
Assets/Scripts/PlayerState.cs
Assets/Scripts/PlayerState.cs.meta

- PlayerController 분리
- PlayerMove
- PlayerStatus
- CameraController(임시)
- 현재 이동이 먹히지 않고 점프 애니매이션만 반복

[FIX][ADD] PlayerController 분리

---

Assets/Materials/HouseInterior/ORG.2.mat
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Assets/Prefabs/SinglePlayerPrefab.prefab
Assets/Prefabs/SinglePlayerPrefab.prefab.meta
Assets/Scenes/TitleScene.unity
Assets/Scenes/ji_SinglePlayScene.unity
Assets/Scripts/Monster/MonsterStatus_S.cs
Assets/Scripts/Single/CameraObstacleHandler.cs
Assets/Scripts/Single/CameraObstacleHandler.cs.meta
Assets/Scripts/Single/Gun_S.cs
Assets/Scripts/Single/Melee_S.cs
Assets/Scripts/Single/ModifiedMonster_S.cs
Assets/Scripts/Single/MonsterController_S.cs
Assets/Scripts/Weapon/Gun.cs
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/TagManager.asset

Feature mg item

---

Assets/Effect/JMO Assets/Cartoon FX FREE (old legacy effects).unitypackage.meta
Assets/Scripts/Item/StatusItemR.cs

[FIX] 유령 아이템 접촉 시 오류 해결

---

Assets/Scenes/ji_SinglePlayScene.unity
Assets/Scripts/Single/InGameUI_S.cs
Assets/Scripts/Single/Melee_S.cs
Assets/Scripts/Single/PlayerStatus_S.cs
Assets/Scripts/Weapon/WeaponData.cs
Assets/Scripts/Weapon/WeaponData.cs.meta
Assets/UI/game over1.png
Assets/UI/game over1.png.meta

[FIX] 게임 종료 UI 수정

---

Assets/Effect/JMO Assets/Cartoon FX FREE (old legacy effects).unitypackage.meta
Assets/Scenes/ji_SinglePlayScene.unity
Assets/Scripts/Single/GameManager_S.cs
Assets/Scripts/Single/PlayerStatus_S.cs
Assets/Scripts/Single/WeaponManager_S.cs
Assets/Scripts/Weapon/weapondata.json

- json 처리 및 무기 줍기 PickUp 하나로  설정

[FIX] 무기 줍기 및 json 수정

---

Assets/Effect/JMO Assets/Cartoon FX FREE (old legacy effects).unitypackage.meta
Assets/Scripts/Multi/PoolingManager.cs
Assets/Scripts/Multi/PoolingManager.cs.meta
ProjectSettings/Packages/com.unity.probuilder/Settings.json

- PoolingManager 스크립트 생성
- MultiPlayScene GhostSpawn 수정

[CHORE] MultiPlay Ghost 관련 수정

---

Assets/Materials/HouseInterior/PNK.1.mat
Assets/Materials/HouseInterior/chair.1.mat
Assets/Materials/HouseInterior/chair.2.mat
Assets/Materials/HouseInterior/chair.mat

[FEAT] 인테리어 구현

---

Assets/Effect/msVFX_Free Smoke Effects Pack.meta
Assets/Effect/msVFX_Free Smoke Effects Pack/Materials.meta
Assets/Effect/msVFX_Free Smoke Effects Pack/Materials/msVFX_Stylized Smoke 1_Material.mat
Assets/Effect/msVFX_Free Smoke Effects Pack/Materials/msVFX_Stylized Smoke 1_Material.mat.meta
Assets/Effect/msVFX_Free Smoke Effects Pack/Textures.meta
Assets/Effect/msVFX_Free Smoke Effects Pack/Textures/msVFX_Stylized Smoke 1_Texture.png
Assets/Effect/msVFX_Free Smoke Effects Pack/Textures/msVFX_Stylized Smoke 1_Texture.png.meta
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Assets/Resources/MultiPlayerPrefab.prefab
Assets/Resources/SmokeParticlePrefab.prefab
Assets/Resources/SmokeParticlePrefab.prefab.meta
Assets/Scenes/TitleScene.unity
Assets/Scripts/Environment/SkyOverTime.cs
Assets/Scripts/Multi/NetworkManager.cs
Assets/Scripts/Multi/PlayerStatus.cs
Assets/Scripts/Single/Melee_S.cs
Assets/Scripts/Single/Monster.cs
Assets/Scripts/Single/PlayerMove_S.cs
Assets/Scripts/Single/WeaponManager_S.cs

- SkyOverTime 스크립트 수정(전등 구현)
- 접속 끊기면 플레이어 오브젝트 삭제되면서 연기 이펙트 발생
- 무기 버릴 때 들고 있던 무기 떨어지는 효과

[FEAT] 부가 기능 구현

---

Assets/Effect/JMO Assets/Cartoon FX FREE (old legacy effects).unitypackage.meta
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Assets/Resources/MultiPlayerPrefab.prefab
Assets/Scenes/TitleScene.unity
Assets/Scripts/Multi/NetworkManager.cs
Assets/Scripts/Multi/PlayerStatus.cs
Assets/Scripts/Single/InGameUI_S.cs
Assets/Scripts/Single/PlayerStatus_S.cs
Assets/Scripts/UI/InGameUI.cs
Assets/Scripts/Weapon/WeaponManager.cs
ProjectSettings/ProjectSettings.asset

전반적인 기능 통합
1. 무기 줍기 및 떨구기
2. 근접 무기 사거리
충돌 해결

기능통합(무기 줍기 및 버릭기, 근접 무기 사거리)

---

Assets/Effect/JMO Assets/Cartoon FX FREE (old legacy effects).unitypackage.meta
Assets/Scripts/Multi/PoolingManager.cs
Assets/Scripts/Single/PoolingManager_S.cs

- 몬스터 풀링 position.y 값 수정: 땅 밑에서 스폰되는 문제 해결

[ADD] PoolingManager 스크립트 수정

---

Assets/Scripts/Single/Weapon/Melee_S.cs

[FIX]Melee attack speed fix

---

Assets/Effect/JMO Assets/Cartoon FX FREE (old legacy effects).unitypackage.meta
Assets/Resources/WeaponData.json
Assets/Scripts/Common/Monster/Monster.cs
Assets/Scripts/Multi/Item/ItemCylinder.cs
Assets/Scripts/Single/Item/WeaponItem_S.cs
Assets/Scripts/Single/Weapon/Melee_S.cs

- 몬스터(싱글)피격 여러 번 되는 현상 고침
- 아이템 리스폰 시간 초 삭제(멀티)
- 각종 버그 픽스

[FIX] 싱글 무기 및 몬스터 피격, 아이템 실린더 시간초 수정

---

Assets/Scripts/Multi/Player/PlayerStatus.cs
Assets/Scripts/Multi/Weapon/Gun.cs
Assets/Scripts/Multi/Weapon/WeaponManager.cs
Assets/Scripts/Single/Player/PlayerStatus_S.cs

- 재장전 중 근거리 무기 줍기 못하게 수정( 싱글, 멀티)
- Sp소모 절반
- 총 공격력 50->20

Feature mg texture

---

Assets/Animations/GhostAnimations/AnimatorGhost.controller
Assets/Scripts/Common/Monster/Monster.cs
Assets/Scripts/Multi/Item/WeaponItem.cs
Assets/Scripts/Single/Item/WeaponItem_S.cs
Assets/Scripts/Single/Player/PlayerStatus_S.cs
Assets/Scripts/Single/Weapon/Gun_S.cs
Assets/Scripts/Single/Weapon/WeaponManager_S.cs

- 몬스터 애니메이션 상태를 더 단순화
- 싱글에서 착용 무기에 상관없이 무기 아이템 줍기 가능
- 싱글 게임 점수 관련 코드 이전
- 멀티 플레이어 스폰 지점 증가
- 건물 파괴 효과 테스트

몬스터 수정, 무기 줍기, 점수 관련, 파괴효과

---

Assets/Animations/GhostAnimations/AnimatorGhost.controller
Assets/Scripts/MeshFracture/Fractures/Fracture.cs

- 파편화 기능에서 더 이상 지원하지 않는 inflateMesh 주석 처리
- 몬스터 피격 애니메이션이 제대로 동작하지 않는 현상 해결(Exit로 가는 트랜지션에 문제가 있었음)

파편화 미지원 함수 주석 처리, 몬스터 피격 애니메이션 수정

---

Assets/Resources/MultiPlayerPrefab.prefab
Assets/Scripts/Common/FadeObjectBlockingObject.cs
Assets/Scripts/Common/MinimapCameraPosition.cs
Assets/Scripts/Common/Weapon/Weapon.cs
Assets/Scripts/Multi/GameManager.cs
Assets/Scripts/Multi/Item/ItemCylinder.cs
Assets/Scripts/Multi/NetworkManager.cs
Assets/Scripts/Multi/Player/PlayerMove.cs
Assets/Scripts/Multi/Player/PlayerStatus.cs
Assets/Scripts/Multi/Weapon/Melee.cs
Assets/Scripts/Single/Item/ItemCylinder_S.cs
Assets/Scripts/Single/Player/PlayerStatus_S.cs
ProjectSettings/Packages/com.unity.probuilder/Settings.json
ProjectSettings/ProjectSettings.asset

- 호스트 마이그레이션 정확도 향상 (RPC 최적화)
- 강도 스테미너 조절

호스트 마이그레이션 및 투명화 오류 해결, 강도 스테이터스 조절
